[project]
name = "aistudy"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "matplotlib",
    "seaborn",
    "numpy",
    "pandas",
    "scipy",
    "scikit-learn",
    "jupyter",
    "torch",
    "torchvision",
    "torchaudio",
]
