[project]
name = "artificial-neural-network"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "puzzzzzzle", email = "2359173906@qq.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
artificial-neural-network = "artificial_neural_network:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
