[project]
name = "open-ai-api-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "puzzzzzzle", email = "2359173906@qq.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
open-ai-api-test = "open_ai_api_test:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
