[project]
name = "machine-learn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "puzzzzzzle", email = "2359173906@qq.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
machine-learn = "machine_learn:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
